swagger: '2.0'
info:
  title: Gatekeeper API
  version: "0.0.0"
host: localhost:8123
schemes:
  - http
  - https
basePath: /api
produces:
  - application/json
paths:
  /version:
    get:
      summary: Gatekeeper version overview
      description: |
        The version endpoint returns the version of the gatekeeper instance running as the current cluster leader.<br>
        Note that the least-significant portion of the version string may differ from request to request as a new cluster leader may have been elected.
      responses:
        200:
          description: Version information
          schema:
            $ref: '#/definitions/Version'
  /replication/info:
    get:
      summary: Replication status overview
      description: |
        The replication info endpoint returns an overview of the current replication state.
      responses:
        200:
          description: Replication status
          schema:
            $ref: '#/definitions/ReplicationStatus'

definitions:
  Version:
    type: object
    properties:
      version:
        type: string
        description: A textual representation of a gatekeeper version
      major:
        type: integer
        description: The major release of this version
      minor:
        type: integer
        description: The minor release of this version
      revision:
        type: integer
        description: The revision number of this release
  ReplicationStatus:
    type: object
    properties:
      type:
        type: string
        description: The type of replication being used
      nodes:
        type: integer
        description: The number of nodes (including this one) in the cluster
      extra:
        type: object
        description: Additional information about replication on a per-provider basis
